### ISSUE TITLE
Fatal error : Class 'Bookingsync\OAuth2\Client\Provider\Bookingsync' not found 

### ISSUE THREAD

**Issue by cvial** [BookingSync/oauth2-bookingsync-php#2]
Hello,

I setup everything but I'm getting this error :

`Fatal error: Uncaught Error: Class 'Bookingsync\OAuth2\Client\Provider\Bookingsync' not found in /var/www/html/bookingsync/examples/api-v3/get_rentals.php:18 Stack trace: #0 {main} thrown in /var/www/html/bookingsync/examples/api-v3/get_rentals.php on line 18`

Is your code working for PHP 7 ?

**Comment by JulienItard** [comment]
Hello @cvial , yes it works on PHP 7. Did you correctly install vendors using composer ?

**Comment by cvial** [comment]
Hello Julien,

Yes I did, the only error I got was the one below:

`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

Could it be the issue?

**Comment by cvial** [comment]
I checked my code and it was my bad, I didn't call the vendor properly, sorry about that !
